name: website_map
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel=7.1.0
  - openpyxl=3.1.5
  - numpy=2.4.0
  - pandas=2.3.3
  - matplotlib=3.10.8
  - plotly=6.5.0
  - pycountry=24.6.1
  - nbformat=5.10.4
  - pip
  - pip:
    - country_converter==1.3.2